### PR TITLE
Fix for issue #34

### PR DESCRIPTION
**Pull request by greim**
https://github.com/greim/hoxy/issues/34

### CODE REVIEW

**Comment by sholladay** [comment]
This is pretty cool. I still can't get the skechers.com test case to display, however. Any idea what's up with that?

**Comment by greim** [comment]
Are you running this branch? I haven't merged or published it to npm yet, but on this branch both test cases render a cheerio-hacked version of the page.

image

image

**Comment by greim** [comment]
Actually now I see an issue, looks like Sketchers xsl file is getting corrupted.

**Comment by greim** [comment]
It looks like cheerio has fundamental issues with XML.

```js
// test.js
var cheerio = require('cheerio')
var input = '<foo title="foo &amp; bar"/>'
var $ = cheerio.load(input,{xmlMode:true})
var output = $.xml()
console.log(input)
console.log(output)
```

```
$ node test.js
<foo title="foo &amp; bar"/>
<foo title="foo & bar"/>
```

**Comment by greim** [comment]
I think the doctype-detection in this branch is still useful since it preserves closing tag conventions on tag-soup html pages, but basically not going to work at all for most real-world xml content. I'll have to think about if/how xml can be exposed (i.e. `as:'xml'` or something) but it likely won't be cheerio since it's not a conforming parser, unless I'm missing something here which is entirely possible.

**Pull request merged**
