### PR TITLE
Allow to remove intercept handlers

### PR DESCRIPTION
**Pull request by freizl**
For add/remove intercept handlers dynamically.

### CODE REVIEW

**Comment by greim** [comment]
This would be a nice addition, but I'd like to stay consistent with other evented APIs, which require passing a reference to the original function object, rather than an `interceptName` string. Something like this:

```js
var phase = 'request';
var handler = function(req, resp){ ... };
proxy.intercept(phase, handler);
proxy.removeIntercept(phase, handler);
```

See for example: http://nodejs.org/api/events.html#events_emitter_removelistener_event_listener

**Comment by freizl** [comment]
This looks better!

And one reason I have name functions is because original handler are 'lost' during wrapping.
If 'remove' function allow passing original function, how to use it to filter out from intercepts.
Any good suggestion?

**Comment by greim** [comment]
I think a reference to the original handler would need to be kept around for that exact reason, like this:

```js
this._intercepts[phase].push({
  handler: intercept,
  originalHandler: originalIntercept
});
```

...to be used solely for the `===` comparison. That feels fragile and error-prone and there's probably a much better way to do it, but hopefully that shows the basic idea.

**Comment by editedredx** [comment]
I'm also interested in being able to remove the interceptors, another option would be to return a remove function from the intercept function

**Comment by greim** [comment]
The more I think about this, the more I'd rather not do it. Interceptors are more like middleware than event handlers. Express and Koa middleware for example can't be dynamically removed, as far as I can tell. It would be easy to do it with a helper in any case:

```js
function stoppable(fn) {
  var isStopped = false;
  var wrapped = function() {
    if (!isStopped) { return fn.apply(this, arguments); }
  }
  wrapped.stop = function() { isStopped = true; };
  wrapped.start = function() { isStopped = false; };
  return wrapped;
}

var intercept = stoppable(function(req, resp, cycle) { ... });

proxy.intercept('request', intercept);

intercept.stop();

intercept.start();
```

That would also be much more flexible than a one-size-fits-all solution. For example, someone would eventually want `stopTemporarily(millis)`, `stopIfCondition(fn)`, or `randomlyStopSomeButNotOthers(probability)` etc. All useful to somebody somewhere, but easily doable with higher-order functions and other helpers.

**Comment by freizl** [comment]
The case I met before is I need "stop"(remove) some interceptors and add back similar ones (intercept same url with different response). 
I'm thinking of adding public `setInterceptor` and `getInterceptor` would be sufficient and allow consumers to decide what they want to do.

**Comment by freizl** [comment]
Closed since I'm not actively working on related now. May come back in future.
Thanks the help!

**Pull request closed without merging**
